"""Vendor the web fonts into fonts/ and regenerate css/fonts.css.

The page used to pull Fraunces and Inter from fonts.googleapis.com. That
stylesheet is render-blocking and it does not name the woff2 files, so the
browser could not start a font download until it had already made a
round trip to a second origin — two serial hops in front of first paint.
Self-hosting collapses both hops into files we can preload by name.

Only the latin and latin-ext subsets are vendored. Everything the page sets
in type lives in latin; latin-ext is carried because it is free — the
unicode-range gate means it is never fetched unless a glyph needs it.

Each file is then instanced down to the weight range the stylesheet actually
declares. Google honours the requested range in the CSS it writes but still
ships the full wght 100..900 design space in the woff2 itself, and those
unused masters are about a fifth of the bytes. The opsz axis is left alone —
index.css sets font-optical-sizing: auto and Fraunces needs it.

Run from the repo root:  python tools/vendor-fonts.py
"""

import io
import os
import re
import urllib.request

from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

# The same request the <link> used to make, minus the subsets we do not ship.
API = (
    "https://fonts.googleapis.com/css2"
    "?family=Fraunces:ital,opsz,wght@0,9..144,400..600;1,9..144,400..600"
    "&family=Inter:wght@400..600"
    "&display=swap"
)

# Google serves woff2 only to browsers that advertise support.
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

SUBSETS = ("latin", "latin-ext")
OUT_DIR = "fonts"
OUT_CSS = "css/fonts.css"

HEADER = """/* ==========================================================================
   Self-hosted web fonts — generated by tools/vendor-fonts.py, do not edit.

   Linked from index.html as its own <link> rather than @import-ed into
   index.css: an @import would put this file behind index.css in a serial
   chain, which is the shape we just removed. The two latin faces the header
   and hero need are preloaded there too, so the woff2 fetches start on the
   HTML parse instead of waiting for this stylesheet to arrive.
   ========================================================================== */
"""


def fetch(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req) as r:
        return r.read() if binary else r.read().decode("utf-8")


def parse(css):
    """Yield (subset, family, style, weight, url) for each @font-face block.

    Google labels every block with a /* subset */ comment on the line above,
    which is the only place the subset name appears.
    """
    for subset, block in re.findall(r"/\* (\S+) \*/\s*@font-face \{(.*?)\}", css, re.S):
        field = lambda name: re.search(rf"{name}: ([^;]+);", block).group(1)
        yield {
            "subset": subset,
            "family": field("font-family").strip("'\""),
            "style": field("font-style"),
            "weight": field("font-weight"),
            "range": field("unicode-range"),
            "url": re.search(r"src: url\((\S+?)\)", block).group(1),
        }


def trim_axes(raw, weight):
    """Cut the variable font down to the weight range the @font-face declares.

    weight is the font-weight descriptor Google wrote, e.g. "400 600". A
    single value would mean a static face, which has no axis to trim.
    """
    bounds = [float(v) for v in weight.split()]
    if len(bounds) != 2:
        return raw

    font = TTFont(io.BytesIO(raw))
    if "fvar" not in font:
        return raw

    font = instancer.instantiateVariableFont(
        font, {"wght": tuple(bounds)}, updateFontNames=False, optimize=True
    )
    out = io.BytesIO()
    font.flavor = "woff2"
    font.save(out)
    return out.getvalue()


def filename(face):
    parts = [face["family"].lower()]
    if face["style"] != "normal":
        parts.append(face["style"])
    parts.append(face["subset"])
    return "-".join(parts) + ".woff2"


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    faces = [f for f in parse(fetch(API)) if f["subset"] in SUBSETS]

    rules = []
    for face in faces:
        name = filename(face)
        path = os.path.join(OUT_DIR, name)
        raw = fetch(face["url"], binary=True)
        trimmed = trim_axes(raw, face["weight"])
        with open(path, "wb") as fh:
            fh.write(trimmed)
        saved = 100 * (len(raw) - len(trimmed)) / len(raw)
        print(f"  {path}  {len(trimmed):,} bytes  (-{saved:.0f}% from {len(raw):,})")

        rules.append(
            "@font-face {\n"
            f"    font-family: '{face['family']}';\n"
            f"    font-style: {face['style']};\n"
            f"    font-weight: {face['weight']};\n"
            "    font-display: swap;\n"
            f"    src: url(../{OUT_DIR}/{name}) format('woff2');\n"
            f"    unicode-range: {face['range']};\n"
            "}"
        )

    with open(OUT_CSS, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(HEADER + "\n" + "\n\n".join(rules) + "\n")
    print(f"  {OUT_CSS}  {len(faces)} faces")


if __name__ == "__main__":
    main()
